version: '3'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: high
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5437:5432"
    volumes: 
      - ./postgres-data:/var/lib/postgresql/data